### ISSUE TITLE
iCloud public calendar - repeat daily not working

### ISSUE THREAD

**Issue by peter-dtm** [grover/homebridge-calendar#2]
Hi
great and useful addition to the HomeKit thank you.

However if I create a daily repeat item; then the sensor is NOT triggered.
If I create a single (none-repeating) sensor then that works perfectly.

If I then EDIT the calendar entry to make it repeat daily; it stops working.

By working I mean that the HomeKit sets the sensor Open for the correct duration.
By not working I mean that the sensor remains Closed.

Setting Notification(s) on/off and/or Busy/Free flags makes no differance

iOS 11.3
Calendar Name : Siri
Sensors set up as 
Siri
Siri2
Siri3
Siri4
18C
19C
20C

The idea I had was to use the Calendar to enforce heating control; whilst allowing some ability to override by manual intervention in Hive or from HomeKit. Obviously I don't want to make an entry for every day of the year .. Siri...Siri4 for general odds and ends 

Comment : The iOS Calendar uses a 5 minute clock; - so to ensure that a 5 minute wide calendar entry (the smallest possible) is detected the homebridge-calendar poll must be set to 4 minutes (unfortunately the timer starts on completion of the check; which can take 4 or 5 seconds; so a 5 minute poll will 'miss' a 5 minute appointment from time to time)

**Comment by dpkcse** [comment]
TypeError: Cannot read property 'calendar' of undefined
    at iCloud.getEvents (/home/dipak/Desktop/outlook/node_modules/apple-icloud/resources/apps/Calendar.js:8:63)
