### ISSUE TITLE
Can you include Telegram

### ISSUE THREAD

**Issue by monza258** [grover/homebridge-calendar#5]
Hello Grover,

Is it possible to include Telegram API? 

Like if Trigger send a Telegram message to ChatID.
I need it about my Lametric Time. :-) There is no Homebridge-Plugin for it  ;-(

If Calender ist Triggert then send me a Telegram message.
IFTTT reads my Telegram Channel and my applet read it and will send a Push notification to my Lametric Time. 

P.s. I can´t send it as a Pull request.

Und gerne auch in Deutsch weiter. =)

**Comment by grover** [comment]
There's my homebridge-telegram plugin for this. Please use HomeKit rules and scenes to configure this any way you want. I'm not inclined to mix Telegram into this plugin.
