### ISSUE TITLE
Deviation from recurring event not handled

### ISSUE THREAD

**Issue by Cinderblox** [grover/homebridge-calendar#6]
I have a calendar with a recurring event at 7AM, let's call it "WakeUp". This works fine and triggers the rule every morning at 7AM. However, when I delete the event for a single day letting it continue after that, the sensor will still trigger at 7AM that day. I guess the sensor will always fire based on the original rule of the recurring event and not based on changes done to single instances of the event done later. 
Polling interval is 15 min, homebridge restart every night.

**Comment by lmelon** [comment]
Hello,

I think I managed to fix the problem. I submitted a pull-request but before it get merged, you can try it by deleting and reinstalling the plugin from this repo: https://github.com/lmelon/homebridge-calendar

**Comment by grover** [comment]
I've merged the PR from @lmelon and published version 0.4.0. I hope this works as expected now. If not, please open another issue.
